# Generated by Django 3.1.12 on 2025-02-01 10:57

import authentication.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='phone',
            field=models.CharField(default='', max_length=10, unique=True, validators=[authentication.accounts.validators.validate_phone]),
        ),
    ]
