# Generated by Django 3.1.12 on 2025-03-26 12:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('due_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_due', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('credit', models.FloatField(default=0.0)),
                ('debit', models.FloatField(default=0.0)),
                ('total', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_bought', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('date_of_purchase', models.DateField()),
                ('paid_amount', models.FloatField(default=0.0)),
                ('due_amount', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
    ]
