# Generated by Django 3.1.12 on 2025-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20250411_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='quantity_bought',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='selling_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='unit_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customerstatement',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customerstatement',
            name='debit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='price',
            field=models.FloatField(),
        ),
    ]
