# Generated by Django 3.1.12 on 2025-02-14 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('due_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('products', models.JSONField(blank=True, default=list, null=True)),
                ('is_due', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_supplied', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('date_of_order', models.DateField()),
                ('paid_amount', models.FloatField(default='')),
                ('due_amount', models.FloatField(default='')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
