# Generated by Django 3.1.12 on 2025-02-07 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('due_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('advance_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('products', models.JSONField(blank=True, default=list, null=True)),
                ('is_due', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
